layout of index
js-tasks-ru/htmlcss-20210409_kolesnikova9292 pull request #3
Opened 2021-04-18 14:02 UTC by kolesnikova9292

2021-04-18 14:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-04-18 15:35 UTC, GSemikozov requested changes

2021-04-24 09:21 UTC, GSemikozov requested changes

2021-04-24 09:21 UTC, GSemikozov commented on assets/css/main.css
> +    box-sizing: border-box;
все эти стили относятся к сбросам дефолтных стилей - советую переместить в normalize.css, так будет правильнее

2021-04-24 09:21 UTC, GSemikozov commented on assets/css/main.css
> +    height: 100vh;
не уверен, но лучше проверить: возможно, если высота контента в main секции будет больше чем высота окна (viewport-а) - невозможно будет проскролить контент ниже. Если это так, тогда лучше использовать height: 100%. Если же все ок - тогда можно ответить здесь в комменте что все ок:)

2021-04-24 09:21 UTC, GSemikozov commented on assets/css/main.css
> +    height: 100%;
если у wrapper-а 100vh то для чего высота в 100% у контейнера?

2021-04-24 09:21 UTC, GSemikozov commented on assets/css/main.css
> +    max-width: calc(100% - 320px);
здесь тоже не совсем понимаю для чего именно такой подсчет. У нас есть четко определенная максимальная ширина контейнера - 1110px, ее и следует указать как `max-width: 1110px`. Чтобы контейнер растянулся на эту ширину - пишем `width: 100%`. И чтобы выровнять контейнер по середине - `margin: auto`. Это стандартный подход для создания таких контейнеров.

2021-04-24 09:21 UTC, GSemikozov commented on components/header/header.css
> +    font-family: Inter;
не вижу - подключен ли этот шрифт?

2021-04-24 09:21 UTC, GSemikozov commented on components/main/main.css
> +    min-height: calc(100% - 264px - 300px);
вот буквально вчера рассказывал что лучше так не делать)) поскольку МР относится к самой первой лекции - я не буду просить исправить именно здесь, но - в последующих МР по лэйауту - обязательно))

2021-04-24 09:21 UTC, GSemikozov commented on components/footer/footer.css
> +    height: 300px;
лучше задать внутренние отступы - паддинги - как в макете, и тогда не нужно будет строго фиксировать высоту

2021-04-24 09:21 UTC, GSemikozov commented on components/footer/footer.css
> +    padding-bottom: 30px;
чтобы не переопределять паддинги лучше воспользоваться развернутой короткой записью - `padding: 70px 70px 30px`.  Но - если нужны отступы от других элементов - это все-таки внешние отступы, а значит - марджины.

2021-04-24 12:39 UTC, kolesnikova9292 commented on assets/css/main.css
> +    height: 100vh;
все ок -  только навернон min-height: 100vh ллучше

2021-04-24 13:11 UTC, kolesnikova9292 commented on components/footer/footer.css
> +@import "./../../assets/css/main.css";
убрала

2021-04-24 13:12 UTC, kolesnikova9292 commented on assets/css/main.css
> +    box-sizing: border-box;
убрала

2021-04-24 13:12 UTC, kolesnikova9292 commented on assets/css/main.css
> +    height: 100vh;
вот с min-height: 100vh работает, я проверила

2021-04-24 13:12 UTC, kolesnikova9292 commented on assets/css/main.css
> +    height: 100%;
да, убрала

2021-04-24 13:13 UTC, kolesnikova9292 commented on assets/css/main.css
> +    max-width: calc(100% - 320px);
согласна - это лишнее, убрала

2021-04-24 13:13 UTC, kolesnikova9292 commented on components/header/header.css
> +    font-family: Inter;
разобралась, подключила

2021-04-24 13:13 UTC, kolesnikova9292 commented on components/main/main.css
> +    min-height: calc(100% - 264px - 300px);
убрала, сделала иначе

2021-04-24 13:13 UTC, kolesnikova9292 commented on components/footer/footer.css
> +    height: 300px;
да, поправила

2021-04-24 13:14 UTC, kolesnikova9292 commented on components/footer/footer.css
> +    padding-bottom: 30px;
я иначе сделала, как ты и советовал ранее, там теперь не такой колхоз

2021-04-24 13:18 UTC, GSemikozov requested changes

2021-04-24 13:18 UTC, GSemikozov commented on components/footer/footer.css
> +    font-family: 'Inter';
после подключения стилей из локальных файлов имя font-family поменялось - теперь у каждого начертания оно свое, нужно везде поправить)

2021-04-24 13:34 UTC, kolesnikova9292 commented on components/footer/footer.css
> +    font-family: 'Inter';
да, поправила

2021-04-24 13:37 UTC, GSemikozov approved these changes

2021-04-24 13:37 UTC, merged