calendar
js-tasks-ru/htmlcss-20210409_kolesnikova9292 pull request #7
Opened 2021-04-26 19:37 UTC by kolesnikova9292

2021-04-27 08:46 UTC, GSemikozov requested changes

2021-04-27 08:46 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding-bottom: 30px;
повторяет верхнее значение, можно удалить

2021-04-27 08:46 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    display: block;
можно просто записать не через span а через div и не переопределять display :)

2021-04-27 08:46 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__content::before {
не совсем понял зачем так делаем - нужно разъяснение :)

2021-04-27 08:46 UTC, GSemikozov commented on assets/css/main.css
> +    --grey_5: rgba(144, 160, 183, .4);
лучше придерживаться единообразного стиля записи имен переменных - если в качестве разделителя выше используется дефис - то лучше его и использовать

2021-04-27 08:46 UTC, GSemikozov commented on assets/fonts/fonts.css
> +    font-family: 'Source Sans Pro';
сверху видно что были добавлены все шрифтовые файлы из архива, но по факту подключаем только 1 - в таких случаях лучше не добавлять лишние файлы если они не используются

2021-05-05 16:48 UTC, kolesnikova9292 commented on 05-lection3/03-calendar/calendar.css
> +    padding-bottom: 30px;
удалила

2021-05-05 16:49 UTC, kolesnikova9292 commented on 05-lection3/03-calendar/calendar.css
> +    display: block;
поправила

2021-05-05 17:06 UTC, kolesnikova9292 commented on 05-lection3/03-calendar/calendar.css
> +.calendar__content::before {
поправила на position, как ты учил

2021-05-05 17:14 UTC, kolesnikova9292 commented on assets/fonts/fonts.css
> +    font-family: 'Source Sans Pro';
почистила неиспользуемые шрифты

2021-05-05 18:19 UTC, GSemikozov requested changes

2021-05-05 18:19 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item:first-child {
а для чего это?)

2021-05-08 11:30 UTC, kolesnikova9292 commented on 05-lection3/03-calendar/calendar.css
> +.calendar__item:first-child {
да - это действительно лишнее - не помню зачем я это добавила - наверное вечер и невнимательность

2021-05-08 13:52 UTC, GSemikozov approved these changes

2021-05-08 13:52 UTC, merged