Template page
js-tasks-ru/htmlcss-20210409_kolesnikova9292 pull request #8
Opened 2021-05-05 18:09 UTC by kolesnikova9292

2021-05-05 18:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-05 18:49 UTC, GSemikozov requested changes

2021-05-05 18:49 UTC, GSemikozov commented on assets/css/main.css
> +    grid-template-columns: minmax(1110px, 300px);
не совсем правильно используется функция minmax - сначала должно идти минимально допустимое значение, затем - максимальное

2021-05-05 18:49 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__descr--template {
--template - это модификатор? если да - лучше дать более точное имя (имя модификатора должно точно указывать на то, ЧТО или КАК он меняет)

2021-05-05 18:49 UTC, GSemikozov commented on components/footer/footer.css
> +.footer__descr--template {
а если это элемент - тогда правильнее писать с одним дефисом.

2021-05-05 18:49 UTC, GSemikozov commented on components/main/main.css
> +    grid-template-rows: repeat(6, auto);
если количество элементов ограничено и должно быть в одну строку - то repeat использовать будет неправильно (в данном случае если появится 7-й элемент - он перенесется на новую строку и меню будет в 2 строки)

2021-05-08 11:54 UTC, kolesnikova9292 commented on assets/css/main.css
> +    grid-template-columns: minmax(1110px, 300px);
поправила, поставила числа наоборот

2021-05-08 11:58 UTC, kolesnikova9292 commented on components/footer/footer.css
> +.footer__descr--template {
Переименовала на container--grid - потому что этот класс основан на гридах.

2021-05-08 12:09 UTC, kolesnikova9292 commented on components/main/main.css
> +    grid-template-rows: repeat(6, auto);
Это свойство необязательно, потому что auto в гридах (насколько я поняла) автоматически ставится.
В две строки не будет, все будет в одну строку. 
И я, если честно, не понимаю, почему все выстроилось в колонку, так, как мне нужно, почему не выстроилось в сетку, пунктики никак не сжались по-дурацки - а все вот так вот в колоночку - как так получилось? - я же задала всего лишь два свойства -     display: grid и grid-row-gap: 10px - всё - но тем не менее - все отрисовалось удачно - почему? - откуда браузер узнал? - подскажи мне пожалуйста

2021-05-08 15:07 UTC, GSemikozov commented on components/main/main.css
> +    grid-template-rows: repeat(6, auto);
ответ в личном сообщении

2021-05-12 19:22 UTC, GSemikozov approved these changes

2021-05-12 19:22 UTC, merged